In [1]:
import gzip
import ast
import json
import pandas as pd
from datetime import datetime

In [2]:
def crearDFJSON(ruta):
    data = []
    with gzip.open(ruta, 'rb') as f:
        for line in f:
            data.append(json.loads(line))
    f.close
    return pd.DataFrame(data)

def crearDFAST(ruta):
    data = []
    with gzip.open(ruta, 'rb') as f:
        for line in f:
            data.append(ast.literal_eval(line.decode('utf-8')))
    f.close
    return pd.DataFrame(data)

def desanidarDF(df, columna):
    df_desanidado = df.explode(columna)
    return df_desanidado

def desanidar(df, columna):
    dfDesanidado = pd.json_normalize(df[columna])
    df = df.reset_index(drop=True)
    df = pd.concat([df, dfDesanidado], axis=1)
    df = df.drop(columna, axis=1)
    return df

In [3]:
steamGamesDF = crearDFJSON('steam_games.json.gz')
userReviews = crearDFAST('user_reviews.json.gz')
usersItems = crearDFAST('users_items.json.gz')

In [8]:
#eliminar nulos e ajustar el indice
steamGamesDF = steamGamesDF.dropna().reset_index(drop=True)

columnas_elimnar = ['url', 'reviews_url', 'early_access', 'genres', 'app_name', 'developer']
tipos = {'publisher':str, 'title':str, 'tags':str, 'specs':str, 'price':float, 'id':str}

steamGamesDF = steamGamesDF.drop(columnas_elimnar, axis=1)
steamGamesDF = desanidarDF(steamGamesDF, 'tags')
steamGamesDF = desanidarDF(steamGamesDF, 'specs')
steamGamesDF = steamGamesDF.reset_index(drop=True)

steamGamesDF['price'] = steamGamesDF['price'].replace('Free To Play', 0)
steamGamesDF['price'] = steamGamesDF['price'].replace('Free to Play', 0)
steamGamesDF['price'] = steamGamesDF['price'].replace('Free', 0)
steamGamesDF['price'] = steamGamesDF['price'].replace('Free Demo', 0)
steamGamesDF['price'] = steamGamesDF['price'].replace('Play for Free!', 0)
steamGamesDF['price'] = steamGamesDF['price'].replace('Install Now', 0)
steamGamesDF['price'] = steamGamesDF['price'].replace('Play WARMACHINE: Tactics Demo', 0)
steamGamesDF['pruserReviewsice'] = steamGamesDF['price'].replace('Free Mod', 0)
steamGamesDF['price'] = steamGamesDF['price'].replace('Play Now', 0)
steamGamesDF['price'] = steamGamesDF['price'].replace('Free HITMAN™ Holiday Pack', 0)
steamGamesDF['price'] = steamGamesDF['price'].replace('Play the Demo', 0)
steamGamesDF['price'] = steamGamesDF['price'].replace('Third-party', 0)

steamGamesDF = steamGamesDF.astype(tipos)
steamGamesDF['price'] = pd.to_numeric(steamGamesDF['price'], errors='coerce')
#steamGamesDF['release_date'] =  pd.to_datetime(steamGamesDF['release_date'], errors='coerce', infer_datetime_format=True)

steamGamesDF.columns = ['Publicador','Titulo','FechaLanzamiento','Etiqueta', 'Especificaciones', 'Precio', 'IdItem']

/tmp/ipykernel_3652/2042944034.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  steamGamesDF['price'] = steamGamesDF['price'].replace('Third-party', 0)

In [9]:
userReviews = desanidarDF(userReviews, 'reviews')
userReviews=desanidar(userReviews, 'reviews')

columnas_elimnar = ['funny', 'last_edited', 'helpful', 'user_url']
userReviews = userReviews.drop(columnas_elimnar, axis=1).reset_index(drop=True)

userReviews.columns = ['IdUsuario', 'Fecha', 'IdItem', 'Recomendado', 'Critica']
userReviews = userReviews.dropna()

In [7]:

columnas_elimnar = ['steam_id', 'user_url']
usersItems = usersItems.drop(columnas_elimnar, axis=1).reset_index(drop=True)

usersItems = desanidarDF(usersItems, 'items')
usersItems = desanidar(usersItems, 'items')
usersItems = usersItems.dropna()

columnas_elimnar = ['playtime_2weeks', 'items_count']
usersItems = usersItems.drop(columnas_elimnar, axis=1).reset_index(drop=True)

In [10]:
steamGamesDF

,Publicador,Titulo,FechaLanzamiento,Etiqueta,Especificaciones,Precio,IdItem
0,Kotoshiro,Lost Summoner Kitty,2018-01-04,Strategy,Single-player,4.99,761140
1,Kotoshiro,Lost Summoner Kitty,2018-01-04,Action,Single-player,4.99,761140
2,Kotoshiro,Lost Summoner Kitty,2018-01-04,Indie,Single-player,4.99,761140
3,Kotoshiro,Lost Summoner Kitty,2018-01-04,Casual,Single-player,4.99,761140
4,Kotoshiro,Lost Summoner Kitty,2018-01-04,Simulation,Single-player,4.99,761140
...,...,...,...,...,...,...,...
592996,SIXNAILS,EXIT 2 - Directions,2017-09-02,Atmospheric,Steam Achievements,4.99,658870
592997,SIXNAILS,EXIT 2 - Directions,2017-09-02,Atmospheric,Steam Cloud,4.99,658870
592998,SIXNAILS,EXIT 2 - Directions,2017-09-02,Relaxing,Single-player,4.99,658870
592999,SIXNAILS,EXIT 2 - Directions,2017-09-02,Relaxing,Steam Achievements,4.99,658870
593000,SIXNAILS,EXIT 2 - Directions,2017-09-02,Relaxing,Steam Cloud,4.99,658870

In [11]:
userReviews

,IdUsuario,Fecha,IdItem,Recomendado,Critica
0,76561197970982479,"Posted November 5, 2011.",1250,True,Simple yet with great replayability. In my opi...
1,76561197970982479,"Posted July 15, 2011.",22200,True,It's unique and worth a playthrough.
2,76561197970982479,"Posted April 21, 2011.",43110,True,Great atmosphere. The gunplay can be a bit chu...
3,js41637,"Posted June 24, 2014.",251610,True,I know what you think when you see this title ...
4,js41637,"Posted September 8, 2013.",227300,True,For a simple (it's actually not all that simpl...
...,...,...,...,...,...
59328,76561198312638244,Posted July 10.,70,True,a must have classic from steam definitely wort...
59329,76561198312638244,Posted July 8.,362890,True,this game is a perfect remake of the original ...
59330,LydiaMorley,Posted July 3.,273110,True,had so much fun plaing this and collecting res...
59331,LydiaMorley,Posted July 20.,730,True,:D
59332,LydiaMorley,Posted July 2.,440,True,so much fun :D

In [12]:
usersItems

,user_id,item_id,item_name,playtime_forever
0,76561197970982479,10,Counter-Strike,6.0
1,76561197970982479,20,Team Fortress Classic,0.0
2,76561197970982479,30,Day of Defeat,7.0
3,76561197970982479,40,Deathmatch Classic,0.0
4,76561197970982479,50,Half-Life: Opposing Force,0.0
...,...,...,...,...
5153204,76561198329548331,346330,BrainBread 2,0.0
5153205,76561198329548331,373330,All Is Dust,0.0
5153206,76561198329548331,388490,One Way To Die: Steam Edition,3.0
5153207,76561198329548331,521570,You Have 10 Seconds 2,4.0
5153208,76561198329548331,519140,Minds Eyes,3.0