In [1]:
import gzip
import ast
import json
import pandas as pd
from datetime import datetime

In [2]:
def crearDFJSON(ruta):
    data = []
    with gzip.open(ruta, 'rb') as f:
        for line in f:
            data.append(json.loads(line))
    f.close
    return pd.DataFrame(data)

def crearDFAST(ruta):
    data = []
    with gzip.open(ruta, 'rb') as f:
        for line in f:
            data.append(ast.literal_eval(line.decode('utf-8')))
    f.close
    return pd.DataFrame(data)

def desanidarDF(df, columna):
    df_desanidado = df.explode(columna)
    return df_desanidado

def desanidar(df, columna):
    dfDesanidado = pd.json_normalize(df[columna])
    df = df.reset_index(drop=True)
    df = pd.concat([df, dfDesanidado], axis=1)
    df = df.drop(columna, axis=1)
    return df

In [3]:
steamGamesDF = crearDFJSON('../data/steam_games.json.gz')
userReviews = crearDFAST('../data/user_reviews.json.gz')
usersItems = crearDFAST('../data/users_items.json.gz')

<h1>Steam Games</h1>

In [21]:
Nombres = steamGamesDF.iloc[:,[3,11]]
Nombres = Nombres.dropna()
Nombres = Nombres.drop_duplicates()
Nombres.columns = ['Titulo', 'IdItem']
Nombres.to_csv('NombresJuegos.csv', index=False)

In [22]:
#eliminar nulos e ajustar el indice
steamGamesDF = steamGamesDF.dropna().reset_index(drop=True)

In [23]:
columnas_elimnar = ['url', 'reviews_url', 'early_access', 'genres', 'app_name', 'developer']
steamGamesDF = steamGamesDF.drop(columnas_elimnar, axis=1)

In [24]:
steamGamesDF = desanidarDF(steamGamesDF, 'tags')
steamGamesDF = desanidarDF(steamGamesDF, 'specs')
steamGamesDF = steamGamesDF.reset_index(drop=True)

In [25]:
steamGamesDF['price'] = steamGamesDF['price'].replace('Free To Play', 0)
steamGamesDF['price'] = steamGamesDF['price'].replace('Free to Play', 0)
steamGamesDF['price'] = steamGamesDF['price'].replace('Free', 0)
steamGamesDF['price'] = steamGamesDF['price'].replace('Free Demo', 0)
steamGamesDF['price'] = steamGamesDF['price'].replace('Play for Free!', 0)
steamGamesDF['price'] = steamGamesDF['price'].replace('Install Now', 0)
steamGamesDF['price'] = steamGamesDF['price'].replace('Play WARMACHINE: Tactics Demo', 0)
steamGamesDF['pruserReviewsice'] = steamGamesDF['price'].replace('Free Mod', 0)
steamGamesDF['price'] = steamGamesDF['price'].replace('Play Now', 0)
steamGamesDF['price'] = steamGamesDF['price'].replace('Free HITMAN™ Holiday Pack', 0)
steamGamesDF['price'] = steamGamesDF['price'].replace('Play the Demo', 0)
steamGamesDF['price'] = steamGamesDF['price'].replace('Third-party', 0)
steamGamesDF['price'] = steamGamesDF['price'].replace('Free Mod', 0)

/tmp/ipykernel_60198/1325692915.py:13: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  steamGamesDF['price'] = steamGamesDF['price'].replace('Free Mod', 0)

In [26]:

tipos = {'publisher':str, 'title':str, 'tags':str, 'specs':str, 'price':float, 'id':str}

steamGamesDF = steamGamesDF.astype(tipos)
steamGamesDF['price'] = pd.to_numeric(steamGamesDF['price'], errors='coerce')

In [27]:
steamGamesDF = steamGamesDF.drop('pruserReviewsice', axis=1)

In [28]:
steamGamesDF.columns = ['Publicador','Titulo','FechaLanzamiento','Etiqueta', 'Especificaciones', 'Precio', 'IdItem']
steamGamesDF = steamGamesDF.drop_duplicates()

In [29]:
columnas_elimnar = ['Publicador', 'Titulo', 'FechaLanzamiento']
steamGamesDF = steamGamesDF.drop(columnas_elimnar, axis=1)

In [30]:
etiquetas_mas_comunes = steamGamesDF['Especificaciones'].value_counts()
etiquetas_mas_comunes

Especificaciones
Single-player                 124052
Steam Achievements             83626
Steam Trading Cards            67662
Steam Cloud                    51170
Full controller support        39439
Multi-player                   33828
Partial Controller Support     26202
Steam Leaderboards             24006
Downloadable Content           20845
Co-op                          16830
Shared/Split Screen            14388
Stats                          12595
Online Multi-Player            12135
Steam Workshop                  9769
Cross-Platform Multiplayer      9046
Includes level editor           8389
Local Multi-Player              6620
Captions available              6224
Online Co-op                    6031
Local Co-op                     5189
MMO                             5086
In-App Purchases                5021
Valve Anti-Cheat enabled        2347
Commentary available            1265
Includes Source SDK              548
Steam Turn Notifications         465
Mods                              86
Mods (require HL2)                43
Game demo                         11
SteamVR Collectibles               3
Name: count, dtype: int64

In [31]:
etiquetas_mas_comunes = steamGamesDF['Etiqueta'].value_counts().head(55)
etiquetas_mas_comunes

Etiqueta
Indie                    54831
Action                   47879
Adventure                30519
Casual                   25503
Strategy                 25103
Simulation               22604
RPG                      17700
Singleplayer             17598
Multiplayer              12219
Great Soundtrack          9600
2D                        8655
Free to Play              7692
Atmospheric               7495
Co-op                     7301
Puzzle                    7110
Sports                    6374
Platformer                6253
Open World                5807
Difficult                 5731
Pixel Graphics            5455
Racing                    5320
Early Access              5274
Shooter                   5220
Sci-fi                    5213
Massively Multiplayer     5151
Funny                     4939
Story Rich                4717
Arcade                    4624
Fantasy                   4538
Anime                     4436
Female Protagonist        4409
Horror                    3983
Retro                     3945
First-Person              3887
Sandbox                   3823
FPS                       3769
Survival                  3583
Local Co-Op               3519
Comedy                    3277
Local Multiplayer         3272
Family Friendly           3082
Turn-Based                3007
Space                     2753
Gore                      2655
Third Person              2615
Classic                   2560
Online Co-Op              2552
Shoot 'Em Up              2546
Controller                2484
Zombies                   2323
Cute                      2307
Tactical                  2245
Rogue-like                2200
Exploration               2182
Point & Click             2103
Name: count, dtype: int64

In [32]:
etiquetas_mas_comunes = steamGamesDF['Etiqueta'].value_counts().head(55)
steamGamesDF = steamGamesDF[steamGamesDF['Etiqueta'].isin(etiquetas_mas_comunes.index)]

In [33]:
etiquetas_mas_comunes = steamGamesDF['Especificaciones'].value_counts().head(24)
steamGamesDF = steamGamesDF[steamGamesDF['Especificaciones'].isin(etiquetas_mas_comunes.index)]

In [34]:
steamGamesDFEtiqueta = steamGamesDF.drop('Especificaciones', axis=1).drop_duplicates()
steamGamesDFEtiqueta

            Etiqueta  Precio  IdItem
0           Strategy    4.99  761140
1             Action    4.99  761140
2              Indie    4.99  761140
3             Casual    4.99  761140
4         Simulation    4.99  761140
...              ...     ...     ...
592983         Indie    4.99  658870
592986        Casual    4.99  658870
592989        Puzzle    4.99  658870
592992  Singleplayer    4.99  658870
592995   Atmospheric    4.99  658870

[102531 rows x 3 columns]

In [35]:
steamGamesDFEspecificaciones = steamGamesDF.drop('Etiqueta', axis=1).drop_duplicates()
steamGamesDFEspecificaciones

                  Especificaciones  Precio  IdItem
0                    Single-player    4.99  761140
5                    Single-player    0.00  643980
6                     Multi-player    0.00  643980
7              Online Multi-Player    0.00  643980
8       Cross-Platform Multiplayer    0.00  643980
...                            ...     ...     ...
592975          Steam Achievements    1.99  610660
592976         Steam Trading Cards    1.99  610660
592983               Single-player    4.99  658870
592984          Steam Achievements    4.99  658870
592985                 Steam Cloud    4.99  658870

[94784 rows x 3 columns]

<h1>User Reviews</h1>

In [36]:
userReviews = desanidarDF(userReviews, 'reviews')
userReviews=desanidar(userReviews, 'reviews')

In [37]:
columnas_elimnar = ['funny', 'last_edited', 'helpful', 'user_url', 'posted', 'review']
userReviews = userReviews.drop(columnas_elimnar, axis=1).reset_index(drop=True)

In [38]:
userReviews.columns = ['IdUsuario','IdItem', 'Recomendado']
userReviews = userReviews.dropna()

In [39]:
userReviews

               IdUsuario  IdItem Recomendado
0      76561197970982479    1250        True
1      76561197970982479   22200        True
2      76561197970982479   43110        True
3                js41637  251610        True
4                js41637  227300        True
...                  ...     ...         ...
59328  76561198312638244      70        True
59329  76561198312638244  362890        True
59330        LydiaMorley  273110        True
59331        LydiaMorley     730        True
59332        LydiaMorley     440        True

[59305 rows x 3 columns]

<h1>Users Items</h1>

In [40]:
columnas_elimnar = ['steam_id', 'user_url']
usersItems = usersItems.drop(columnas_elimnar, axis=1).reset_index(drop=True)

In [41]:
usersItems = desanidarDF(usersItems, 'items')
usersItems = desanidar(usersItems, 'items')

In [42]:
usersItems = usersItems.dropna()

In [43]:
usersItems = usersItems.drop_duplicates()

In [44]:

columnas_elimnar = ['playtime_2weeks', 'items_count', 'item_name']
usersItems = usersItems.drop(columnas_elimnar, axis=1).reset_index(drop=True)

In [45]:
usersItems = usersItems[usersItems['playtime_forever'] != 0]

In [46]:
usersItems.columns = ['IdUsuario','IdItem', 'Tiempo_Jugado']

In [47]:
# Calcular el tiempo jugado promedio por 'IdItem'
tiempo_promedio_por_item = usersItems.groupby('IdItem')['Tiempo_Jugado'].mean()

# Convertir la serie resultante en un DataFrame con la columna 'Tiempo_Jugado_Promedio'
tiempo_promedio_por_item_df = tiempo_promedio_por_item.reset_index().rename(columns={'Tiempo_Jugado': 'Tiempo_Jugado_Promedio'})

# Fusionar el DataFrame original con el nuevo DataFrame que contiene el tiempo jugado promedio por 'IdItem'
usersItems = pd.merge(usersItems, tiempo_promedio_por_item_df, on='IdItem', how='left')

In [48]:
usersItems[usersItems['IdItem'] == '362890']

,IdUsuario,IdItem,Tiempo_Jugado,Tiempo_Jugado_Promedio
636,js41637,362890,338.0,599.461538
1536,MinxIsBetterThanPotatoes,362890,509.0,599.461538
2640,76561198089393905,362890,109.0,599.461538
3237,thequeenpanda,362890,263.0,599.461538
6005,jarrodtrim,362890,389.0,599.461538
...,...,...,...,...
3230576,AMarioL,362890,795.0,599.461538
3232532,allanhammon,362890,949.0,599.461538
3240502,massimo23,362890,849.0,599.461538
3242634,76561198203947177,362890,713.0,599.461538
3246344,76561198312638244,362890,2184.0,599.461538

<h1>Union</h2>

In [49]:
df_merged = pd.merge(usersItems, userReviews, on=['IdUsuario', 'IdItem'])
df_merged = pd.merge(df_merged, steamGamesDFEtiqueta, on=['IdItem'])
columnas_elimnar = ['IdUsuario','Tiempo_Jugado']
df_merged = df_merged.drop(columnas_elimnar, axis=1)
df_merged['Recomendado'] = df_merged['Recomendado'].astype(int)

# Obtener variables dummy para columnas específicas
df_merged = pd.get_dummies(df_merged, columns=['Etiqueta']).astype(int)
df_merged = df_merged.drop_duplicates()
df_merged = df_merged.dropna()

In [50]:
df_merged

,IdItem,Tiempo_Jugado_Promedio,Recomendado,Precio,Etiqueta_2D,Etiqueta_Action,Etiqueta_Adventure,Etiqueta_Anime,Etiqueta_Arcade,Etiqueta_Atmospheric,...,Etiqueta_Singleplayer,Etiqueta_Space,Etiqueta_Sports,Etiqueta_Story Rich,Etiqueta_Strategy,Etiqueta_Survival,Etiqueta_Tactical,Etiqueta_Third Person,Etiqueta_Turn-Based,Etiqueta_Zombies
0,22200,190,1,9,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,22200,190,1,9,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,22200,190,1,9,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,22200,190,1,9,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,22200,190,1,9,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
506094,431510,667,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
506095,431510,667,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
506096,431510,667,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
506097,431510,667,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
506098,431510,667,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [51]:
df_merged2 = pd.merge(usersItems, userReviews, on=['IdUsuario', 'IdItem'])
df_merged2 = pd.merge(df_merged2, steamGamesDFEspecificaciones, on=['IdItem'])
columnas_elimnar = ['IdUsuario','Tiempo_Jugado']
df_merged2 = df_merged2.drop(columnas_elimnar, axis=1)
df_merged2['Recomendado'] = df_merged2['Recomendado'].astype(int)

# Obtener variables dummy para columnas específicas
df_merged2 = pd.get_dummies(df_merged2, columns=['Especificaciones']).astype(int)
df_merged2 = df_merged2.drop_duplicates()
df_merged2 = df_merged2.dropna()

In [52]:
df_merged2

,IdItem,Tiempo_Jugado_Promedio,Recomendado,Precio,Especificaciones_Captions available,Especificaciones_Co-op,Especificaciones_Commentary available,Especificaciones_Cross-Platform Multiplayer,Especificaciones_Downloadable Content,Especificaciones_Full controller support,...,Especificaciones_Partial Controller Support,Especificaciones_Shared/Split Screen,Especificaciones_Single-player,Especificaciones_Stats,Especificaciones_Steam Achievements,Especificaciones_Steam Cloud,Especificaciones_Steam Leaderboards,Especificaciones_Steam Trading Cards,Especificaciones_Steam Workshop,Especificaciones_Valve Anti-Cheat enabled
0,22200,190,1,9,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1,22200,190,1,9,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,22200,190,1,9,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,22200,190,1,9,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
4,1250,2265,1,19,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242504,220090,179,1,8,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
242526,431510,667,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
242527,431510,667,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
242528,431510,667,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
242529,431510,667,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [53]:
df_merged.to_csv('ETL_ETIQUETAS.csv', index=False)
df_merged2.to_csv('ETL_ESPECIFICACIONES.csv', index=False)